// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(LCIM_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define LCIM_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if LCIM_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/LCIMProtocolBuffers.h>
#else
 #import "LCIMProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class LCIMAny;
@class LCIMEnumValue;
@class LCIMField;
@class LCIMOption;
@class LCIMSourceContext;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum GPBSyntax

/** The syntax in which a protocol buffer element is defined. */
typedef GPB_ENUM(GPBSyntax) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  GPBSyntax_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Syntax `proto2`. */
  GPBSyntax_SyntaxProto2 = 0,

  /** Syntax `proto3`. */
  GPBSyntax_SyntaxProto3 = 1,
};

LCIMEnumDescriptor *LCIMSyntax_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL LCIMSyntax_IsValidValue(int32_t value);

#pragma mark - Enum LCIMField_Kind

/** Basic field types. */
typedef GPB_ENUM(LCIMField_Kind) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  LCIMField_Kind_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Field type unknown. */
  LCIMField_Kind_TypeUnknown = 0,

  /** Field type double. */
  LCIMField_Kind_TypeDouble = 1,

  /** Field type float. */
  LCIMField_Kind_TypeFloat = 2,

  /** Field type int64. */
  LCIMField_Kind_TypeInt64 = 3,

  /** Field type uint64. */
  LCIMField_Kind_TypeUint64 = 4,

  /** Field type int32. */
  LCIMField_Kind_TypeInt32 = 5,

  /** Field type fixed64. */
  LCIMField_Kind_TypeFixed64 = 6,

  /** Field type fixed32. */
  LCIMField_Kind_TypeFixed32 = 7,

  /** Field type bool. */
  LCIMField_Kind_TypeBool = 8,

  /** Field type string. */
  LCIMField_Kind_TypeString = 9,

  /** Field type group. Proto2 syntax only, and deprecated. */
  LCIMField_Kind_TypeGroup = 10,

  /** Field type message. */
  LCIMField_Kind_TypeMessage = 11,

  /** Field type bytes. */
  LCIMField_Kind_TypeBytes = 12,

  /** Field type uint32. */
  LCIMField_Kind_TypeUint32 = 13,

  /** Field type enum. */
  LCIMField_Kind_TypeEnum = 14,

  /** Field type sfixed32. */
  LCIMField_Kind_TypeSfixed32 = 15,

  /** Field type sfixed64. */
  LCIMField_Kind_TypeSfixed64 = 16,

  /** Field type sint32. */
  LCIMField_Kind_TypeSint32 = 17,

  /** Field type sint64. */
  LCIMField_Kind_TypeSint64 = 18,
};

LCIMEnumDescriptor *LCIMField_Kind_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL LCIMField_Kind_IsValidValue(int32_t value);

#pragma mark - Enum LCIMField_Cardinality

/** Whether a field is optional, required, or repeated. */
typedef GPB_ENUM(LCIMField_Cardinality) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  LCIMField_Cardinality_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** For fields with unknown cardinality. */
  LCIMField_Cardinality_CardinalityUnknown = 0,

  /** For optional fields. */
  LCIMField_Cardinality_CardinalityOptional = 1,

  /** For required fields. Proto2 syntax only. */
  LCIMField_Cardinality_CardinalityRequired = 2,

  /** For repeated fields. */
  LCIMField_Cardinality_CardinalityRepeated = 3,
};

LCIMEnumDescriptor *LCIMField_Cardinality_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL LCIMField_Cardinality_IsValidValue(int32_t value);

#pragma mark - LCIMTypeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface LCIMTypeRoot : LCIMRootObject
@end

#pragma mark - LCIMType

typedef GPB_ENUM(LCIMType_FieldNumber) {
  LCIMType_FieldNumber_Name = 1,
  LCIMType_FieldNumber_FieldsArray = 2,
  LCIMType_FieldNumber_OneofsArray = 3,
  LCIMType_FieldNumber_OptionsArray = 4,
  LCIMType_FieldNumber_SourceContext = 5,
  LCIMType_FieldNumber_Syntax = 6,
};

/**
 * A protocol buffer message type.
 **/
@interface LCIMType : LCIMMessage

/** The fully qualified message name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** The list of fields. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCIMField*> *fieldsArray;
/** The number of items in @c fieldsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger fieldsArray_Count;

/** The list of types appearing in `oneof` definitions in this type. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *oneofsArray;
/** The number of items in @c oneofsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger oneofsArray_Count;

/** The protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCIMOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The source context. */
@property(nonatomic, readwrite, strong, null_resettable) LCIMSourceContext *sourceContext;
/** Test to see if @c sourceContext has been set. */
@property(nonatomic, readwrite) BOOL hasSourceContext;

/** The source syntax. */
@property(nonatomic, readwrite) GPBSyntax syntax;

@end

/**
 * Fetches the raw value of a @c LCIMType's @c syntax property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LCIMType_Syntax_RawValue(LCIMType *message);
/**
 * Sets the raw value of an @c LCIMType's @c syntax property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLCIMType_Syntax_RawValue(LCIMType *message, int32_t value);

#pragma mark - LCIMField

typedef GPB_ENUM(LCIMField_FieldNumber) {
  LCIMField_FieldNumber_Kind = 1,
  LCIMField_FieldNumber_Cardinality = 2,
  LCIMField_FieldNumber_Number = 3,
  LCIMField_FieldNumber_Name = 4,
  LCIMField_FieldNumber_TypeURL = 6,
  LCIMField_FieldNumber_OneofIndex = 7,
  LCIMField_FieldNumber_Packed = 8,
  LCIMField_FieldNumber_OptionsArray = 9,
  LCIMField_FieldNumber_JsonName = 10,
  LCIMField_FieldNumber_DefaultValue = 11,
};

/**
 * A single field of a message type.
 **/
@interface LCIMField : LCIMMessage

/** The field type. */
@property(nonatomic, readwrite) LCIMField_Kind kind;

/** The field cardinality. */
@property(nonatomic, readwrite) LCIMField_Cardinality cardinality;

/** The field number. */
@property(nonatomic, readwrite) int32_t number;

/** The field name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * The field type URL, without the scheme, for message or enumeration
 * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *typeURL;

/**
 * The index of the field type in `Type.oneofs`, for message or enumeration
 * types. The first type has index 1; zero means the type is not in the list.
 **/
@property(nonatomic, readwrite) int32_t oneofIndex;

/** Whether to use alternative packed wire representation. */
@property(nonatomic, readwrite) BOOL packed;

/** The protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCIMOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The field JSON name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *jsonName;

/** The string value of the default value of this field. Proto2 syntax only. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *defaultValue;

@end

/**
 * Fetches the raw value of a @c LCIMField's @c kind property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LCIMField_Kind_RawValue(LCIMField *message);
/**
 * Sets the raw value of an @c LCIMField's @c kind property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLCIMField_Kind_RawValue(LCIMField *message, int32_t value);

/**
 * Fetches the raw value of a @c LCIMField's @c cardinality property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LCIMField_Cardinality_RawValue(LCIMField *message);
/**
 * Sets the raw value of an @c LCIMField's @c cardinality property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLCIMField_Cardinality_RawValue(LCIMField *message, int32_t value);

#pragma mark - LCIMEnum

typedef GPB_ENUM(LCIMEnum_FieldNumber) {
  LCIMEnum_FieldNumber_Name = 1,
  LCIMEnum_FieldNumber_EnumvalueArray = 2,
  LCIMEnum_FieldNumber_OptionsArray = 3,
  LCIMEnum_FieldNumber_SourceContext = 4,
  LCIMEnum_FieldNumber_Syntax = 5,
};

/**
 * Enum type definition.
 **/
@interface LCIMEnum : LCIMMessage

/** Enum type name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Enum value definitions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCIMEnumValue*> *enumvalueArray;
/** The number of items in @c enumvalueArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger enumvalueArray_Count;

/** Protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCIMOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The source context. */
@property(nonatomic, readwrite, strong, null_resettable) LCIMSourceContext *sourceContext;
/** Test to see if @c sourceContext has been set. */
@property(nonatomic, readwrite) BOOL hasSourceContext;

/** The source syntax. */
@property(nonatomic, readwrite) GPBSyntax syntax;

@end

/**
 * Fetches the raw value of a @c LCIMEnum's @c syntax property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LCIMEnum_Syntax_RawValue(LCIMEnum *message);
/**
 * Sets the raw value of an @c LCIMEnum's @c syntax property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLCIMEnum_Syntax_RawValue(LCIMEnum *message, int32_t value);

#pragma mark - LCIMEnumValue

typedef GPB_ENUM(LCIMEnumValue_FieldNumber) {
  LCIMEnumValue_FieldNumber_Name = 1,
  LCIMEnumValue_FieldNumber_Number = 2,
  LCIMEnumValue_FieldNumber_OptionsArray = 3,
};

/**
 * Enum value definition.
 **/
@interface LCIMEnumValue : LCIMMessage

/** Enum value name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Enum value number. */
@property(nonatomic, readwrite) int32_t number;

/** Protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCIMOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

@end

#pragma mark - LCIMOption

typedef GPB_ENUM(LCIMOption_FieldNumber) {
  LCIMOption_FieldNumber_Name = 1,
  LCIMOption_FieldNumber_Value = 2,
};

/**
 * A protocol buffer option, which can be attached to a message, field,
 * enumeration, etc.
 **/
@interface LCIMOption : LCIMMessage

/** The option's name. For example, `"java_package"`. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** The option's value. For example, `"com.google.protobuf"`. */
@property(nonatomic, readwrite, strong, null_resettable) LCIMAny *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
