// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(LCGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define LCGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if LCGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/LCGPBDescriptor.h>
 #import <protobuf/LCGPBMessage.h>
 #import <protobuf/LCGPBRootObject.h>
#else
 #import "LCGPBDescriptor.h"
 #import "LCGPBMessage.h"
 #import "LCGPBRootObject.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class LCGPBAny;
@class LCGPBEnumValue;
@class LCGPBField;
@class LCGPBOption;
@class LCGPBSourceContext;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum LCGPBSyntax

/** The syntax in which a protocol buffer element is defined. */
typedef LCGPB_ENUM(LCGPBSyntax) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  LCGPBSyntax_LCGPBUnrecognizedEnumeratorValue = kLCGPBUnrecognizedEnumeratorValue,
  /** Syntax `proto2`. */
  LCGPBSyntax_SyntaxProto2 = 0,

  /** Syntax `proto3`. */
  LCGPBSyntax_SyntaxProto3 = 1,
};

LCGPBEnumDescriptor *LCGPBSyntax_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL LCGPBSyntax_IsValidValue(int32_t value);

#pragma mark - Enum LCGPBField_Kind

/** Basic field types. */
typedef LCGPB_ENUM(LCGPBField_Kind) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  LCGPBField_Kind_LCGPBUnrecognizedEnumeratorValue = kLCGPBUnrecognizedEnumeratorValue,
  /** Field type unknown. */
  LCGPBField_Kind_TypeUnknown = 0,

  /** Field type double. */
  LCGPBField_Kind_TypeDouble = 1,

  /** Field type float. */
  LCGPBField_Kind_TypeFloat = 2,

  /** Field type int64. */
  LCGPBField_Kind_TypeInt64 = 3,

  /** Field type uint64. */
  LCGPBField_Kind_TypeUint64 = 4,

  /** Field type int32. */
  LCGPBField_Kind_TypeInt32 = 5,

  /** Field type fixed64. */
  LCGPBField_Kind_TypeFixed64 = 6,

  /** Field type fixed32. */
  LCGPBField_Kind_TypeFixed32 = 7,

  /** Field type bool. */
  LCGPBField_Kind_TypeBool = 8,

  /** Field type string. */
  LCGPBField_Kind_TypeString = 9,

  /** Field type group. Proto2 syntax only, and deprecated. */
  LCGPBField_Kind_TypeGroup = 10,

  /** Field type message. */
  LCGPBField_Kind_TypeMessage = 11,

  /** Field type bytes. */
  LCGPBField_Kind_TypeBytes = 12,

  /** Field type uint32. */
  LCGPBField_Kind_TypeUint32 = 13,

  /** Field type enum. */
  LCGPBField_Kind_TypeEnum = 14,

  /** Field type sfixed32. */
  LCGPBField_Kind_TypeSfixed32 = 15,

  /** Field type sfixed64. */
  LCGPBField_Kind_TypeSfixed64 = 16,

  /** Field type sint32. */
  LCGPBField_Kind_TypeSint32 = 17,

  /** Field type sint64. */
  LCGPBField_Kind_TypeSint64 = 18,
};

LCGPBEnumDescriptor *LCGPBField_Kind_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL LCGPBField_Kind_IsValidValue(int32_t value);

#pragma mark - Enum LCGPBField_Cardinality

/** Whether a field is optional, required, or repeated. */
typedef LCGPB_ENUM(LCGPBField_Cardinality) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  LCGPBField_Cardinality_LCGPBUnrecognizedEnumeratorValue = kLCGPBUnrecognizedEnumeratorValue,
  /** For fields with unknown cardinality. */
  LCGPBField_Cardinality_CardinalityUnknown = 0,

  /** For optional fields. */
  LCGPBField_Cardinality_CardinalityOptional = 1,

  /** For required fields. Proto2 syntax only. */
  LCGPBField_Cardinality_CardinalityRequired = 2,

  /** For repeated fields. */
  LCGPBField_Cardinality_CardinalityRepeated = 3,
};

LCGPBEnumDescriptor *LCGPBField_Cardinality_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL LCGPBField_Cardinality_IsValidValue(int32_t value);

#pragma mark - LCGPBTypeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (LCGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c LCGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface LCGPBTypeRoot : LCGPBRootObject
@end

#pragma mark - LCGPBType

typedef LCGPB_ENUM(LCGPBType_FieldNumber) {
  LCGPBType_FieldNumber_Name = 1,
  LCGPBType_FieldNumber_FieldsArray = 2,
  LCGPBType_FieldNumber_OneofsArray = 3,
  LCGPBType_FieldNumber_OptionsArray = 4,
  LCGPBType_FieldNumber_SourceContext = 5,
  LCGPBType_FieldNumber_Syntax = 6,
};

/**
 * A protocol buffer message type.
 **/
@interface LCGPBType : LCGPBMessage

/** The fully qualified message name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** The list of fields. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCGPBField*> *fieldsArray;
/** The number of items in @c fieldsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger fieldsArray_Count;

/** The list of types appearing in `oneof` definitions in this type. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *oneofsArray;
/** The number of items in @c oneofsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger oneofsArray_Count;

/** The protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The source context. */
@property(nonatomic, readwrite, strong, null_resettable) LCGPBSourceContext *sourceContext;
/** Test to see if @c sourceContext has been set. */
@property(nonatomic, readwrite) BOOL hasSourceContext;

/** The source syntax. */
@property(nonatomic, readwrite) LCGPBSyntax syntax;

@end

/**
 * Fetches the raw value of a @c LCGPBType's @c syntax property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LCGPBType_Syntax_RawValue(LCGPBType *message);
/**
 * Sets the raw value of an @c LCGPBType's @c syntax property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLCGPBType_Syntax_RawValue(LCGPBType *message, int32_t value);

#pragma mark - LCGPBField

typedef LCGPB_ENUM(LCGPBField_FieldNumber) {
  LCGPBField_FieldNumber_Kind = 1,
  LCGPBField_FieldNumber_Cardinality = 2,
  LCGPBField_FieldNumber_Number = 3,
  LCGPBField_FieldNumber_Name = 4,
  LCGPBField_FieldNumber_TypeURL = 6,
  LCGPBField_FieldNumber_OneofIndex = 7,
  LCGPBField_FieldNumber_Packed = 8,
  LCGPBField_FieldNumber_OptionsArray = 9,
  LCGPBField_FieldNumber_JsonName = 10,
  LCGPBField_FieldNumber_DefaultValue = 11,
};

/**
 * A single field of a message type.
 **/
@interface LCGPBField : LCGPBMessage

/** The field type. */
@property(nonatomic, readwrite) LCGPBField_Kind kind;

/** The field cardinality. */
@property(nonatomic, readwrite) LCGPBField_Cardinality cardinality;

/** The field number. */
@property(nonatomic, readwrite) int32_t number;

/** The field name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * The field type URL, without the scheme, for message or enumeration
 * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *typeURL;

/**
 * The index of the field type in `Type.oneofs`, for message or enumeration
 * types. The first type has index 1; zero means the type is not in the list.
 **/
@property(nonatomic, readwrite) int32_t oneofIndex;

/** Whether to use alternative packed wire representation. */
@property(nonatomic, readwrite) BOOL packed;

/** The protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The field JSON name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *jsonName;

/** The string value of the default value of this field. Proto2 syntax only. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *defaultValue;

@end

/**
 * Fetches the raw value of a @c LCGPBField's @c kind property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LCGPBField_Kind_RawValue(LCGPBField *message);
/**
 * Sets the raw value of an @c LCGPBField's @c kind property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLCGPBField_Kind_RawValue(LCGPBField *message, int32_t value);

/**
 * Fetches the raw value of a @c LCGPBField's @c cardinality property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LCGPBField_Cardinality_RawValue(LCGPBField *message);
/**
 * Sets the raw value of an @c LCGPBField's @c cardinality property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLCGPBField_Cardinality_RawValue(LCGPBField *message, int32_t value);

#pragma mark - LCGPBEnum

typedef LCGPB_ENUM(LCGPBEnum_FieldNumber) {
  LCGPBEnum_FieldNumber_Name = 1,
  LCGPBEnum_FieldNumber_EnumvalueArray = 2,
  LCGPBEnum_FieldNumber_OptionsArray = 3,
  LCGPBEnum_FieldNumber_SourceContext = 4,
  LCGPBEnum_FieldNumber_Syntax = 5,
};

/**
 * Enum type definition.
 **/
@interface LCGPBEnum : LCGPBMessage

/** Enum type name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Enum value definitions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCGPBEnumValue*> *enumvalueArray;
/** The number of items in @c enumvalueArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger enumvalueArray_Count;

/** Protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The source context. */
@property(nonatomic, readwrite, strong, null_resettable) LCGPBSourceContext *sourceContext;
/** Test to see if @c sourceContext has been set. */
@property(nonatomic, readwrite) BOOL hasSourceContext;

/** The source syntax. */
@property(nonatomic, readwrite) LCGPBSyntax syntax;

@end

/**
 * Fetches the raw value of a @c LCGPBEnum's @c syntax property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LCGPBEnum_Syntax_RawValue(LCGPBEnum *message);
/**
 * Sets the raw value of an @c LCGPBEnum's @c syntax property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLCGPBEnum_Syntax_RawValue(LCGPBEnum *message, int32_t value);

#pragma mark - LCGPBEnumValue

typedef LCGPB_ENUM(LCGPBEnumValue_FieldNumber) {
  LCGPBEnumValue_FieldNumber_Name = 1,
  LCGPBEnumValue_FieldNumber_Number = 2,
  LCGPBEnumValue_FieldNumber_OptionsArray = 3,
};

/**
 * Enum value definition.
 **/
@interface LCGPBEnumValue : LCGPBMessage

/** Enum value name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Enum value number. */
@property(nonatomic, readwrite) int32_t number;

/** Protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LCGPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

@end

#pragma mark - LCGPBOption

typedef LCGPB_ENUM(LCGPBOption_FieldNumber) {
  LCGPBOption_FieldNumber_Name = 1,
  LCGPBOption_FieldNumber_Value = 2,
};

/**
 * A protocol buffer option, which can be attached to a message, field,
 * enumeration, etc.
 **/
@interface LCGPBOption : LCGPBMessage

/**
 * The option's name. For protobuf built-in options (options defined in
 * descriptor.proto), this is the short name. For example, `"map_entry"`.
 * For custom options, it should be the fully-qualified name. For example,
 * `"google.api.http"`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * The option's value packed in an Any message. If the value is a primitive,
 * the corresponding wrapper type defined in google/protobuf/wrappers.proto
 * should be used. If the value is an enum, it should be stored as an int32
 * value using the google.protobuf.Int32Value type.
 **/
@property(nonatomic, readwrite, strong, null_resettable) LCGPBAny *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
